nodeMetadata: {}
istio:
  default: true # create all applicable istio resources for root namespace
jitter:
  workloads: "20s"
  config: "10s"
namespaces:
- name: mesh
  replicas: 1
  istio:
    sidecar: {} # create sidecar istio resource for each replica of 'mesh' namespace
  applications:
  - name: big
    replicas: 10
    instances: 6
    istio:
      # create virtualService istio resource for each replica of 'big' application with referencing 'main' gateway
      virtualService:
        gateways: [main]
      sidecar: {} # create sidecar istio resource for each replica of 'big' application
  - name: small
    replicas: 200
    instances: 10
    istio:
      # create virtualService istio resource for each replica of 'small' application with referencing 'main' gateway
      virtualService:
        gateways: [ main ]
      destinationRule: {} # create destinationRule istio resource for each replica of 'small' application
- name: gateway
  replicas: 1
  applications:
  - name: ingress
    replicas: 1
    instances: 1
    appType: router
    gateways: # create istio gateway for 'ingress' application
      name: main
      enabled: true