apiVersion: v1
kind: Pod
spec:
  initContainers:
  - name: sidecar
    image: "alpine:3.12.3"
    restartPolicy: Always
    command: ["nc", "-lk", "-p", "12346", "-e", "echo", "hi"]
    readinessProbe:
      tcpSocket:
        port: 12346
      initialDelaySeconds: 0
      periodSeconds: 1
      successThreshold: 1
      failureThreshold: 1
    startupProbe:
      tcpSocket:
        port: 12346
      initialDelaySeconds: 0
      periodSeconds: 1
      successThreshold: 1
      failureThreshold: 1
  containers:
  - name: app
    image: "alpine:3.12.3"
    command: ["nc", "-lk", "-p", "12345", "-e", "echo", "hi"]
    readinessProbe:
      tcpSocket:
        port: 12345
      initialDelaySeconds: 0
      periodSeconds: 1
      successThreshold: 1
      failureThreshold: 1
  terminationGracePeriodSeconds: 0
