apiVersion: v1
kind: ConfigMap
metadata:
  name: pilot-load-config
  namespace: pilot-load
data:
  # Can be used with a real API server; creates GW/VS/Secrets
  config.yaml: |
    jitter:
      secrets: "5s"
    namespaces:
    - name: gateway
      replicas: 1
      istio:
        default: true
      applications:
      - name: ingress
        replicas: 1
        instances: 0
        istio:
          default: true
        type: router
        gateways:
          name: main
          replicas: 100
          enabled: true
