{
 "title": "Pilot Load Dashbard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Istiod", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"istiod\"}",
     "legendFormat": "Resident Memory"
    },
    {
     "expr": "go_memstats_alloc_bytes{app=\"istiod\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{app=\"istiod\"}",
     "legendFormat": "Heap in-use"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{app=\"istiod\"}",
     "legendFormat": "Stack in-use"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=\"discovery\", pod=~\"istiod-.*\"}[1m]))",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container=\"discovery\", pod=~\"istiod-.*\"}[5m]))",
     "legendFormat": "Rolling Average CPU"
    },
    {
     "expr": "sum(irate(container_cpu_cfs_throttled_seconds_total{container=\"discovery\", pod=~\"istiod-.*\"}[1m]))",
     "legendFormat": "Throttled"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{app=\"istiod\"}",
     "legendFormat": "{{quantile}}"
    },
    {
     "expr": "go_memstats_gc_cpu_fraction{app=\"istiod\"}",
     "legendFormat": "GC CPU Percentage"
    }
   ]
  },
  {
   "title": "Config Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_k8s_cfg_events{event!=\"updatesame\"}[1m])) by (type, event)",
     "legendFormat": "{{event}} {{type}}"
    }
   ]
  },
  {
   "title": "Registry Events",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_k8s_reg_events{event=~\"add\"}[1m])) by (type, event)",
     "legendFormat": "{{event}} {{type}}"
    },
    {
     "expr": "-sum(irate(pilot_k8s_reg_events{event=\"delete\"}[1m])) by (type, event)",
     "legendFormat": "{{event}} {{type}}"
    },
    {
     "expr": "sum(irate(pilot_k8s_reg_events{event=~\"update\"}[1m])) by (type, event)",
     "legendFormat": "{{event}} {{type}}"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(pilot_xds)", "legendFormat": "Connected XDS Clients" }
   ]
  },
  {
   "title": "Pilot Pushes",
   "type": "graph",
   "description": "Shows the rate of pilot pushes",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_xds_pushes{type=\"cds\"}[1m]))",
     "legendFormat": "Cluster"
    },
    {
     "expr": "sum(irate(pilot_xds_pushes{type=\"eds\"}[1m]))",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(irate(pilot_xds_pushes{type=\"lds\"}[1m]))",
     "legendFormat": "Listeners"
    },
    {
     "expr": "sum(irate(pilot_xds_pushes{type=\"rds\"}[1m]))",
     "legendFormat": "Routes"
    }
   ]
  },
  {
   "title": "Push Triggers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(pilot_push_triggers[1m])) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Proxy Push Time",
   "type": "graph",
   "description": "Shows the total time it takes to push a config update to a proxy",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
     "legendFormat": "p50 "
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(pilot_proxy_convergence_time_bucket[1m])) by (le))",
     "legendFormat": "p99.9"
    }
   ]
  },
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"apiserver-.*\", container=\"apiserver\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_memory_usage_bytes{pod=~\"etcd-.*\", container=\"etcd\"}",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "container_memory_usage_bytes{pod=~\"pilot-load-.*\", container=\"pilot-load\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(container_cpu_usage_seconds_total{pod=~\"apiserver-.*\", container=\"apiserver\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{pod=~\"etcd-.*\", container=\"etcd\"}[1m])",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "irate(container_cpu_usage_seconds_total{pod=~\"pilot-load-.*\", container=\"pilot-load\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Resource Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(etcd_object_counts{resource=~\"pods|namespaces|services|gateways.networking.istio.io|virtualservices.networking.istio.io\"}) by (resource)\n",
     "legendFormat": "{{resource}}"
    }
   ]
  }
 ]
}