apiVersion: apps/v1
kind: Deployment
metadata:
  name: pilot-load
  namespace: pilot-load
  labels:
    app: pilot-load
spec:
  replicas: 1
  template:
    metadata:
      name: pilot-load
      annotations:
        sidecar.istio.io/inject: "false"
        prometheus.io/scrape: "true"
        prometheus.io/port: "8765"
      labels:
        app: pilot-load
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              namespaces: [istio-system]
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - istiod
              topologyKey: kubernetes.io/hostname
      # May take a while to shut down
      terminationGracePeriodSeconds: 2000
      containers:
      - name: pilot-load
        image: gcr.io/howardjohn-istio/pilot-load
        imagePullPolicy: Always
        args:
          - "cluster"
          - "--pilot-address=istiod.istio-system:15010"
          - "--config=/etc/config/config/config.yaml"
          - "--qps=5000"
        env:
        - name: KUBECONFIG
          value: /etc/config/kubeconfig/kubeconfig.yaml
        resources:
          requests:
            cpu: 4000m
            memory: 4Gi
        volumeMounts:
        - name: kubeconfig
          mountPath: /etc/config/kubeconfig
        - name: config
          mountPath: /etc/config/config
      volumes:
      - name: kubeconfig
        configMap:
          name: pilot-load-kubeconfig
      - name: config
        configMap:
          name: pilot-load-config
  selector:
    matchLabels:
      app: pilot-load
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pilot-load-kubeconfig
  namespace: pilot-load
data:
  kubeconfig.yaml: |
    apiVersion: v1
    clusters:
    - cluster:
        server: http://apiserver.pilot-load:18090
      name: load
    contexts:
    - context:
        cluster: load
        user: fake
      name: load
    current-context: load
    kind: Config
    preferences: {}
    users:
    - name: fake
