apiVersion: v1
clusters:
- cluster:
    server: http://localhost:18090
  name: load
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUtQZnplTzdLRXFXbXBITmxlUVFkUWd3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05UUXpORFUwTWpNdE1XWTJPQzAwTmpRMkxUbGtaREl0TTJJMU0yTmhNMkppWTJOaApNQ0FYRFRJek1ESXlNREE0TlRRek9Gb1lEekl3TlRNd01qRXlNRGsxTkRNNFdqQXZNUzB3S3dZRFZRUURFeVExCk5ETTBOVFF5TXkweFpqWTRMVFEyTkRZdE9XUmtNaTB6WWpVelkyRXpZbUpqWTJFd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDcmxtMEZ6UUV2ckpxa0ZpbSs3NGxGTkNDMWYyekdCMjcvTndNZgpOMmRpcmdTNHlTL3lkVTk4VjRnNG5EcWRnR3FMVFhhNnlOVFNvQXNpbzZ6cmFHVVFUTVN0RUcxRWtiMTNuSFJFCkdIWVNnTFFYRksza1loRkpPV2ZwYUpZVTdlaS9EVGxxWTNubkxEK1N2Mi9LbFN0K1piWGdLSFVxc2Q2blcrdzUKQVMyNm1uQ2RVSHVrSXlFaUs4MlcvaHg4ZWtDZythYmxNcjlDZU5Kc0ZuRVM0eGx2S2tNZXowdU9zdmFiYVl3MQpvOWV3cUtVeGJrblNtTSszYnJ3Mm8vQVRSanNtMGhYcFp3L2p1UDRnV2RYNTFJU1doSVFxYnJBdFM3WU1YSUlJCmZjeXJ6ZlFod05aQVYwb0JJNGQ4T1h5Vlk5S0ZsT1hieHZTTXRuVnRJcy9vQ1FqU2xhOEtOWExsZzV0NmdDT08KYnIycjhKRjN0bG1UY041WW1BZE5GcG5nOEJEcTVUa25FNEhObTJ3Zm9GVHZCd2VRVjVJU2ZDcjhQT3VuMFJpRAptR2pEWXVhbXZsaFhObmxtemdMSGxqb0phL3FJRGtHVlRKZ0ZyUTVPd2tlM2ZCWlA3SVE1Q05oRU5yUnkySnlyCnBtWjZTNEFyUVI0WXhyWm9CVUdWc1YwZnhNMENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTW83OE1XSmFaQWxpbnk2Qko5MTZ1SE96TFhUTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQVRRcDB6cnY4aXRGc3pCdzVkWDN1NHZuUUpmZGVuSTJkY2ZmV1ZnTzNYCjQwSTNWWEFTVWVpMHBLNzJQaFBmeUU0MVlReEVGbDhQdVV0RXEzUFRZQkQvRGs5T1ZBdXBRYjRmeklUU3A0TGIKWW03UytESTcxbisrOVlvS1d6dzhjcE9WbEJlZXZRTFQ5Qk4zalJiNVVXcnhybHRzR21QTTBoT1VEWTZvQUlKSApnRmhXNm95MFJsSlV2RWlGTURPcnRxQTdBdnRmMzRCMmNoOXFmSEhkekJzOHBQeFpOS3Q4Z1FyWmdkM2J5YWE2Cnh5ZEcwRXRmcThENVQwZU94ZTk1RWU5S1BuMHQxNkZ5eG9aOUVET0hxL0JncjR4cmFwK1Y4dGUrMnZqUG9MN1YKTHV0bXdlWjR4OUVoS3FicGNFYjBmK28wMzZxNy80VmxEZlV3OTRlQVp6bnd5Z0YyanR5dVZOUVQwWEtmdTU2bQpFbGV2NHlNYzFybGR5TXFaVGpkbHoxTHltcnV0OFVaZGZMcTFKcmg3YXYxajJvZU41MTU0emx3MTZJY0h0VlNqCmZTSjc0eEsvdkhHdGMybjk5dTBYUXpRSXZIYWFDcC9ybnJRaS9uWkdMNVBVbmtWODF2SncreXpLamFrUi9qTDQKci9zeWRBZFFvSjR1bitnQUxFRkczM3M9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.67.108.67
  name: gke_a4vm-hemendrat_us-central1-c_cluster-6
contexts:
- context:
    cluster: load
    namespace: pilot-load
    user: fake
  name: load
- context:
    cluster: gke_a4vm-hemendrat_us-central1-c_cluster-6
    user: gke_a4vm-hemendrat_us-central1-c_cluster-6
  name: gke_a4vm-hemendrat_us-central1-c_cluster-6
current-context: gke_a4vm-hemendrat_us-central1-c_cluster-6
kind: Config
preferences: {}
users:
- name: fake
  user: {}
- name: gke_a4vm-hemendrat_us-central1-c_cluster-6
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      provideClusterInfo: true
